// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core_lighting`, `split`, `translate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// The engine's version.
String version() => RustLib.instance.api.crateApiLusterVersion();

/// The panorama the badge reflects (equirectangular): the showcase's.
Future<Texture> showcaseEnvironment() =>
    RustLib.instance.api.crateApiLusterShowcaseEnvironment();

/// The badge's reverse: a tangent-space normal map of sandblasted metal, the
/// same for every badge.
Future<Texture> sandblast() => RustLib.instance.api.crateApiLusterSandblast();

Rgba defaultGold() => RustLib.instance.api.crateApiLusterDefaultGold();

Rgba silver() => RustLib.instance.api.crateApiLusterSilver();

Rgba copper() => RustLib.instance.api.crateApiLusterCopper();

LightingPreset lightingPreset({required Lighting lighting}) =>
    RustLib.instance.api.crateApiLusterLightingPreset(lighting: lighting);

SceneCalibration sceneCalibration() =>
    RustLib.instance.api.crateApiLusterSceneCalibration();

/// RealityKit's tone mapping as a `.cube` table, for flutter_scene to draw
/// through with no tone curve of its own: a scene exposed by
/// `SceneCalibration.exposure`, clamped and read through it, shows what
/// RealityKit would.
Future<String> realitykitToneCube() =>
    RustLib.instance.api.crateApiLusterRealitykitToneCube();

Finish finish({required MaterialRole role, required Lighting lighting}) =>
    RustLib.instance.api.crateApiLusterFinish(role: role, lighting: lighting);

/// What a lamp is worth in the preset's units; multiply by `scene_lux`.
double lamp({required LightRole role, required Lighting lighting}) =>
    RustLib.instance.api.crateApiLusterLamp(role: role, lighting: lighting);

List<Light> studioLights() => RustLib.instance.api.crateApiLusterStudioLights();

Camera studioCamera() => RustLib.instance.api.crateApiLusterStudioCamera();

/// The camera's vertical field of view, degrees, for a badge `width` by
/// `height` across in a view `aspect` wide over tall.
double fieldOfView({
  required double width,
  required double height,
  required double aspect,
}) => RustLib.instance.api.crateApiLusterFieldOfView(
  width: width,
  height: height,
  aspect: aspect,
);

Handling handling() => RustLib.instance.api.crateApiLusterHandling();

/// Carries a flick's spin (radians per second) over `dt` seconds.
Coast coast({required double velocity, required double dt}) =>
    RustLib.instance.api.crateApiLusterCoast(velocity: velocity, dt: dt);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MintRequest>>
abstract class MintRequest implements RustOpaqueInterface {
  /// The badge, once it is struck; a `cancelled` error once given up.
  Future<LusterBadge> badge();

  /// Gives the badge up: `badge` ends `cancelled`, and the engine stops if
  /// nobody else wants it. Nothing once it has come.
  void cancel();

  factory MintRequest({required List<int> svg, required MintOptions options}) =>
      RustLib.instance.api.crateApiLusterMintRequestNew(
        svg: svg,
        options: options,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Struck>>
abstract class Struck implements RustOpaqueInterface {
  /// The badge as a glTF binary: see `LusterBadge.glb` in Dart.
  Future<Uint8List> glb({required double scale, required Rgba metal});
}

/// Where the camera stands.
class Camera {
  final double fov;
  final double distance;

  const Camera({required this.fov, required this.distance});

  @override
  int get hashCode => fov.hashCode ^ distance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Camera &&
          runtimeType == other.runtimeType &&
          fov == other.fov &&
          distance == other.distance;
}

/// How far a flick carries the badge over a frame, and the spin it is left with.
class Coast {
  final double turn;
  final double velocity;

  const Coast({required this.turn, required this.velocity});

  @override
  int get hashCode => turn.hashCode ^ velocity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Coast &&
          runtimeType == other.runtimeType &&
          turn == other.turn &&
          velocity == other.velocity;
}

/// How one of the badge's materials is finished under a lighting.
class Finish {
  final double metallic;
  final double roughness;

  /// How much a dielectric reflects, as a part of glass's 4% head on:
  /// glTF's `KHR_materials_specular` factor. Metal takes no notice of it.
  final double specular;

  /// Coloured by the metal the badge is plated in, rather than by the
  /// material's own colour.
  final bool plated;

  const Finish({
    required this.metallic,
    required this.roughness,
    required this.specular,
    required this.plated,
  });

  @override
  int get hashCode =>
      metallic.hashCode ^
      roughness.hashCode ^
      specular.hashCode ^
      plated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Finish &&
          runtimeType == other.runtimeType &&
          metallic == other.metallic &&
          roughness == other.roughness &&
          specular == other.specular &&
          plated == other.plated;
}

/// How the badge answers a drag, the same on every platform.
class Handling {
  /// Radians per logical pixel dragged.
  final double spinPerPoint;
  final double tiltPerPoint;
  final double tiltLimit;

  /// Where the badge sits before it is touched, radians.
  final double restingTilt;
  final double restingSpin;

  const Handling({
    required this.spinPerPoint,
    required this.tiltPerPoint,
    required this.tiltLimit,
    required this.restingTilt,
    required this.restingSpin,
  });

  @override
  int get hashCode =>
      spinPerPoint.hashCode ^
      tiltPerPoint.hashCode ^
      tiltLimit.hashCode ^
      restingTilt.hashCode ^
      restingSpin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Handling &&
          runtimeType == other.runtimeType &&
          spinPerPoint == other.spinPerPoint &&
          tiltPerPoint == other.tiltPerPoint &&
          tiltLimit == other.tiltLimit &&
          restingTilt == other.restingTilt &&
          restingSpin == other.restingSpin;
}

/// A lamp in the studio: which way it points, and what colour it is.
class Light {
  final LightRole role;
  final Rgba color;

  /// Which way it shines, already in flutter_scene's left-handed space.
  final Float32List direction;

  const Light({
    required this.role,
    required this.color,
    required this.direction,
  });

  @override
  int get hashCode => role.hashCode ^ color.hashCode ^ direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Light &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          color == other.color &&
          direction == other.direction;
}

enum LightRole {
  key,
  fill,
  back,

  /// Rides on the camera, pointing where it looks.
  headlight,
}

/// See `LusterLighting` in Dart.
enum Lighting { showcase, off }

/// What flutter_scene needs of a lighting: how much of the environment to
/// take, and what the lamps are worth here. What each lamp and material is
/// given comes from `lamp` and `finish`.
class LightingPreset {
  /// What the environment is worth here: flutter_scene's
  /// `environmentIntensity`.
  final double environment;
  final double sceneLux;

  const LightingPreset({required this.environment, required this.sceneLux});

  @override
  int get hashCode => environment.hashCode ^ sceneLux.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightingPreset &&
          runtimeType == other.runtimeType &&
          environment == other.environment &&
          sceneLux == other.sceneLux;
}

class LusterBadge {
  final String designKey;
  final List<Submesh> submeshes;
  final List<Material> materials;
  final List<Texture> textures;

  /// The badge as the engine struck it, which is what a GLB is written from:
  /// the arrays above are already in flutter_scene's space.
  final Struck struck;

  const LusterBadge({
    required this.designKey,
    required this.submeshes,
    required this.materials,
    required this.textures,
    required this.struck,
  });

  @override
  int get hashCode =>
      designKey.hashCode ^
      submeshes.hashCode ^
      materials.hashCode ^
      textures.hashCode ^
      struck.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LusterBadge &&
          runtimeType == other.runtimeType &&
          designKey == other.designKey &&
          submeshes == other.submeshes &&
          materials == other.materials &&
          textures == other.textures &&
          struck == other.struck;
}

/// Why a badge could not be minted: thrown to Dart.
class LusterError implements FrbException {
  final LusterErrorKind kind;

  /// What the engine said, for a person to read.
  final String reason;

  const LusterError({required this.kind, required this.reason});

  @override
  int get hashCode => kind.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LusterError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          reason == other.reason;
}

/// What went wrong, as the other bindings tell it apart.
enum LusterErrorKind {
  invalidSvg,
  inputTooComplex,
  nothingToMint,
  cancelled,

  /// Dart's `LusterErrorKind.engineFailure`.
  internal,
}

class Material {
  final String name;
  final MaterialRole role;
  final Rgba color;
  final double metallic;
  final double roughness;

  /// A texture for the front face, where the document's colour changes
  /// across it; indexes the badge's textures.
  final int? texture;

  const Material({
    required this.name,
    required this.role,
    required this.color,
    required this.metallic,
    required this.roughness,
    this.texture,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      role.hashCode ^
      color.hashCode ^
      metallic.hashCode ^
      roughness.hashCode ^
      texture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Material &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          role == other.role &&
          color == other.color &&
          metallic == other.metallic &&
          roughness == other.roughness &&
          texture == other.texture;
}

enum MaterialRole {
  plated,
  goldBack,
  field,
  art,

  /// Metal plated in the document's colours: a metal, in the colour it
  /// carries rather than the metal's.
  glaze,
}

/// What to strike: see `LusterOptions` in Dart.
class MintOptions {
  final bool withoutHiddenFaces;
  final bool metalLines;

  const MintOptions({
    required this.withoutHiddenFaces,
    required this.metalLines,
  });

  @override
  int get hashCode => withoutHiddenFaces.hashCode ^ metalLines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintOptions &&
          runtimeType == other.runtimeType &&
          withoutHiddenFaces == other.withoutHiddenFaces &&
          metalLines == other.metalLines;
}

/// sRGB, straight alpha.
class Rgba {
  final double r;
  final double g;
  final double b;
  final double a;

  const Rgba({
    required this.r,
    required this.g,
    required this.b,
    required this.a,
  });

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode ^ a.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Rgba &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b &&
          a == other.a;
}

/// What the studio is worth to flutter_scene whatever the lighting.
class SceneCalibration {
  final double exposure;

  /// What a lamp's intensity, times `scene_lux`, is worth here.
  final double lampUnit;

  const SceneCalibration({required this.exposure, required this.lampUnit});

  @override
  int get hashCode => exposure.hashCode ^ lampUnit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SceneCalibration &&
          runtimeType == other.runtimeType &&
          exposure == other.exposure &&
          lampUnit == other.lampUnit;
}

/// One submesh as separate attribute arrays, the shape flutter_scene's
/// `MeshGeometry.fromArrays` takes, in flutter_scene's left-handed space: the
/// engine's z is negated (the badge's face looks down -z) and triangles are
/// wound the other way to match.
class Submesh {
  final String name;
  final int material;
  final Float32List positions;
  final Float32List normals;
  final Float32List texCoords;
  final Float32List tangents;
  final Uint32List indices;

  const Submesh({
    required this.name,
    required this.material,
    required this.positions,
    required this.normals,
    required this.texCoords,
    required this.tangents,
    required this.indices,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      material.hashCode ^
      positions.hashCode ^
      normals.hashCode ^
      texCoords.hashCode ^
      tangents.hashCode ^
      indices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Submesh &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          material == other.material &&
          positions == other.positions &&
          normals == other.normals &&
          texCoords == other.texCoords &&
          tangents == other.tangents &&
          indices == other.indices;
}

/// RGBA8, sRGB, rows top to bottom.
class Texture {
  final int width;
  final int height;
  final Uint8List rgba;

  const Texture({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Texture &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}
