// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/luster.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 116726236;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'luster_dart',
        ioDirectory: '../../rust/crates/luster-dart/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<LusterBadge> crateApiLusterMintRequestBadge({
    required MintRequest that,
  });

  void crateApiLusterMintRequestCancel({required MintRequest that});

  MintRequest crateApiLusterMintRequestNew({
    required List<int> svg,
    required MintOptions options,
  });

  Future<Uint8List> crateApiLusterStruckGlb({
    required Struck that,
    required double scale,
    required Rgba metal,
  });

  Coast crateApiLusterCoast({required double velocity, required double dt});

  Rgba crateApiLusterCopper();

  Rgba crateApiLusterDefaultGold();

  double crateApiLusterFieldOfView({
    required double width,
    required double height,
    required double aspect,
  });

  Finish crateApiLusterFinish({
    required MaterialRole role,
    required Lighting lighting,
  });

  Handling crateApiLusterHandling();

  double crateApiLusterLamp({
    required LightRole role,
    required Lighting lighting,
  });

  LightingPreset crateApiLusterLightingPreset({required Lighting lighting});

  Future<String> crateApiLusterRealitykitToneCube();

  Future<Texture> crateApiLusterSandblast();

  SceneCalibration crateApiLusterSceneCalibration();

  Future<Texture> crateApiLusterShowcaseEnvironment();

  Rgba crateApiLusterSilver();

  Camera crateApiLusterStudioCamera();

  List<Light> crateApiLusterStudioLights();

  String crateApiLusterVersion();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MintRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MintRequest;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MintRequestPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Struck;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Struck;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_StruckPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<LusterBadge> crateApiLusterMintRequestBadge({
    required MintRequest that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_luster_badge,
          decodeErrorData: sse_decode_luster_error,
        ),
        constMeta: kCrateApiLusterMintRequestBadgeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterMintRequestBadgeConstMeta =>
      const TaskConstMeta(debugName: "MintRequest_badge", argNames: ["that"]);

  @override
  void crateApiLusterMintRequestCancel({required MintRequest that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterMintRequestCancelConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterMintRequestCancelConstMeta =>
      const TaskConstMeta(debugName: "MintRequest_cancel", argNames: ["that"]);

  @override
  MintRequest crateApiLusterMintRequestNew({
    required List<int> svg,
    required MintOptions options,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(svg, serializer);
          sse_encode_box_autoadd_mint_options(options, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterMintRequestNewConstMeta,
        argValues: [svg, options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterMintRequestNewConstMeta =>
      const TaskConstMeta(
        debugName: "MintRequest_new",
        argNames: ["svg", "options"],
      );

  @override
  Future<Uint8List> crateApiLusterStruckGlb({
    required Struck that,
    required double scale,
    required Rgba metal,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
            that,
            serializer,
          );
          sse_encode_f_32(scale, serializer);
          sse_encode_box_autoadd_rgba(metal, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterStruckGlbConstMeta,
        argValues: [that, scale, metal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterStruckGlbConstMeta => const TaskConstMeta(
    debugName: "Struck_glb",
    argNames: ["that", "scale", "metal"],
  );

  @override
  Coast crateApiLusterCoast({required double velocity, required double dt}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(velocity, serializer);
          sse_encode_f_32(dt, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_coast,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterCoastConstMeta,
        argValues: [velocity, dt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterCoastConstMeta =>
      const TaskConstMeta(debugName: "coast", argNames: ["velocity", "dt"]);

  @override
  Rgba crateApiLusterCopper() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rgba,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterCopperConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterCopperConstMeta =>
      const TaskConstMeta(debugName: "copper", argNames: []);

  @override
  Rgba crateApiLusterDefaultGold() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rgba,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterDefaultGoldConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterDefaultGoldConstMeta =>
      const TaskConstMeta(debugName: "default_gold", argNames: []);

  @override
  double crateApiLusterFieldOfView({
    required double width,
    required double height,
    required double aspect,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_32(width, serializer);
          sse_encode_f_32(height, serializer);
          sse_encode_f_32(aspect, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterFieldOfViewConstMeta,
        argValues: [width, height, aspect],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterFieldOfViewConstMeta => const TaskConstMeta(
    debugName: "field_of_view",
    argNames: ["width", "height", "aspect"],
  );

  @override
  Finish crateApiLusterFinish({
    required MaterialRole role,
    required Lighting lighting,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_material_role(role, serializer);
          sse_encode_lighting(lighting, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_finish,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterFinishConstMeta,
        argValues: [role, lighting],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterFinishConstMeta =>
      const TaskConstMeta(debugName: "finish", argNames: ["role", "lighting"]);

  @override
  Handling crateApiLusterHandling() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_handling,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterHandlingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterHandlingConstMeta =>
      const TaskConstMeta(debugName: "handling", argNames: []);

  @override
  double crateApiLusterLamp({
    required LightRole role,
    required Lighting lighting,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_light_role(role, serializer);
          sse_encode_lighting(lighting, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterLampConstMeta,
        argValues: [role, lighting],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterLampConstMeta =>
      const TaskConstMeta(debugName: "lamp", argNames: ["role", "lighting"]);

  @override
  LightingPreset crateApiLusterLightingPreset({required Lighting lighting}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_lighting(lighting, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lighting_preset,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterLightingPresetConstMeta,
        argValues: [lighting],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterLightingPresetConstMeta =>
      const TaskConstMeta(debugName: "lighting_preset", argNames: ["lighting"]);

  @override
  Future<String> crateApiLusterRealitykitToneCube() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterRealitykitToneCubeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterRealitykitToneCubeConstMeta =>
      const TaskConstMeta(debugName: "realitykit_tone_cube", argNames: []);

  @override
  Future<Texture> crateApiLusterSandblast() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_texture,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterSandblastConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterSandblastConstMeta =>
      const TaskConstMeta(debugName: "sandblast", argNames: []);

  @override
  SceneCalibration crateApiLusterSceneCalibration() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scene_calibration,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterSceneCalibrationConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterSceneCalibrationConstMeta =>
      const TaskConstMeta(debugName: "scene_calibration", argNames: []);

  @override
  Future<Texture> crateApiLusterShowcaseEnvironment() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_texture,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterShowcaseEnvironmentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterShowcaseEnvironmentConstMeta =>
      const TaskConstMeta(debugName: "showcase_environment", argNames: []);

  @override
  Rgba crateApiLusterSilver() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rgba,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterSilverConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterSilverConstMeta =>
      const TaskConstMeta(debugName: "silver", argNames: []);

  @override
  Camera crateApiLusterStudioCamera() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_camera,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterStudioCameraConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterStudioCameraConstMeta =>
      const TaskConstMeta(debugName: "studio_camera", argNames: []);

  @override
  List<Light> crateApiLusterStudioLights() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_light,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterStudioLightsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterStudioLightsConstMeta =>
      const TaskConstMeta(debugName: "studio_lights", argNames: []);

  @override
  String crateApiLusterVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLusterVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLusterVersionConstMeta =>
      const TaskConstMeta(debugName: "version", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_MintRequest => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_MintRequest => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Struck => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Struck => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck;

  @protected
  Struck
  dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
      raw,
    );
  }

  @protected
  MintRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MintRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Struck
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StruckImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MintRequest
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MintRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Struck
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StruckImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  MintRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MintRequestImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Struck
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StruckImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MintOptions dco_decode_box_autoadd_mint_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mint_options(raw);
  }

  @protected
  Rgba dco_decode_box_autoadd_rgba(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_rgba(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Camera dco_decode_camera(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Camera(
      fov: dco_decode_f_32(arr[0]),
      distance: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  Coast dco_decode_coast(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Coast(
      turn: dco_decode_f_32(arr[0]),
      velocity: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Finish dco_decode_finish(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Finish(
      metallic: dco_decode_f_32(arr[0]),
      roughness: dco_decode_f_32(arr[1]),
      specular: dco_decode_f_32(arr[2]),
      plated: dco_decode_bool(arr[3]),
    );
  }

  @protected
  Handling dco_decode_handling(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Handling(
      spinPerPoint: dco_decode_f_32(arr[0]),
      tiltPerPoint: dco_decode_f_32(arr[1]),
      tiltLimit: dco_decode_f_32(arr[2]),
      restingTilt: dco_decode_f_32(arr[3]),
      restingSpin: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Light dco_decode_light(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Light(
      role: dco_decode_light_role(arr[0]),
      color: dco_decode_rgba(arr[1]),
      direction: dco_decode_list_prim_f_32_strict(arr[2]),
    );
  }

  @protected
  LightRole dco_decode_light_role(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LightRole.values[raw as int];
  }

  @protected
  Lighting dco_decode_lighting(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Lighting.values[raw as int];
  }

  @protected
  LightingPreset dco_decode_lighting_preset(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LightingPreset(
      environment: dco_decode_f_32(arr[0]),
      sceneLux: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  List<Light> dco_decode_list_light(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_light).toList();
  }

  @protected
  List<Material> dco_decode_list_material(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_material).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Submesh> dco_decode_list_submesh(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_submesh).toList();
  }

  @protected
  List<Texture> dco_decode_list_texture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_texture).toList();
  }

  @protected
  LusterBadge dco_decode_luster_badge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LusterBadge(
      designKey: dco_decode_String(arr[0]),
      submeshes: dco_decode_list_submesh(arr[1]),
      materials: dco_decode_list_material(arr[2]),
      textures: dco_decode_list_texture(arr[3]),
      struck:
          dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
            arr[4],
          ),
    );
  }

  @protected
  LusterError dco_decode_luster_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LusterError(
      kind: dco_decode_luster_error_kind(arr[0]),
      reason: dco_decode_String(arr[1]),
    );
  }

  @protected
  LusterErrorKind dco_decode_luster_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LusterErrorKind.values[raw as int];
  }

  @protected
  Material dco_decode_material(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Material(
      name: dco_decode_String(arr[0]),
      role: dco_decode_material_role(arr[1]),
      color: dco_decode_rgba(arr[2]),
      metallic: dco_decode_f_32(arr[3]),
      roughness: dco_decode_f_32(arr[4]),
      texture: dco_decode_opt_box_autoadd_u_32(arr[5]),
    );
  }

  @protected
  MaterialRole dco_decode_material_role(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MaterialRole.values[raw as int];
  }

  @protected
  MintOptions dco_decode_mint_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MintOptions(
      withoutHiddenFaces: dco_decode_bool(arr[0]),
      metalLines: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Rgba dco_decode_rgba(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Rgba(
      r: dco_decode_f_32(arr[0]),
      g: dco_decode_f_32(arr[1]),
      b: dco_decode_f_32(arr[2]),
      a: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  SceneCalibration dco_decode_scene_calibration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SceneCalibration(
      exposure: dco_decode_f_32(arr[0]),
      lampUnit: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  Submesh dco_decode_submesh(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Submesh(
      name: dco_decode_String(arr[0]),
      material: dco_decode_u_32(arr[1]),
      positions: dco_decode_list_prim_f_32_strict(arr[2]),
      normals: dco_decode_list_prim_f_32_strict(arr[3]),
      texCoords: dco_decode_list_prim_f_32_strict(arr[4]),
      tangents: dco_decode_list_prim_f_32_strict(arr[5]),
      indices: dco_decode_list_prim_u_32_strict(arr[6]),
    );
  }

  @protected
  Texture dco_decode_texture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Texture(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Struck
  sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner =
        sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
          deserializer,
        );
    return inner;
  }

  @protected
  MintRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MintRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Struck
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return StruckImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MintRequest
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MintRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Struck
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return StruckImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  MintRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return MintRequestImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Struck
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return StruckImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MintOptions sse_decode_box_autoadd_mint_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mint_options(deserializer));
  }

  @protected
  Rgba sse_decode_box_autoadd_rgba(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_rgba(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  Camera sse_decode_camera(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fov = sse_decode_f_32(deserializer);
    var var_distance = sse_decode_f_32(deserializer);
    return Camera(fov: var_fov, distance: var_distance);
  }

  @protected
  Coast sse_decode_coast(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_turn = sse_decode_f_32(deserializer);
    var var_velocity = sse_decode_f_32(deserializer);
    return Coast(turn: var_turn, velocity: var_velocity);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  Finish sse_decode_finish(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_metallic = sse_decode_f_32(deserializer);
    var var_roughness = sse_decode_f_32(deserializer);
    var var_specular = sse_decode_f_32(deserializer);
    var var_plated = sse_decode_bool(deserializer);
    return Finish(
      metallic: var_metallic,
      roughness: var_roughness,
      specular: var_specular,
      plated: var_plated,
    );
  }

  @protected
  Handling sse_decode_handling(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_spinPerPoint = sse_decode_f_32(deserializer);
    var var_tiltPerPoint = sse_decode_f_32(deserializer);
    var var_tiltLimit = sse_decode_f_32(deserializer);
    var var_restingTilt = sse_decode_f_32(deserializer);
    var var_restingSpin = sse_decode_f_32(deserializer);
    return Handling(
      spinPerPoint: var_spinPerPoint,
      tiltPerPoint: var_tiltPerPoint,
      tiltLimit: var_tiltLimit,
      restingTilt: var_restingTilt,
      restingSpin: var_restingSpin,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Light sse_decode_light(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_light_role(deserializer);
    var var_color = sse_decode_rgba(deserializer);
    var var_direction = sse_decode_list_prim_f_32_strict(deserializer);
    return Light(role: var_role, color: var_color, direction: var_direction);
  }

  @protected
  LightRole sse_decode_light_role(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LightRole.values[inner];
  }

  @protected
  Lighting sse_decode_lighting(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Lighting.values[inner];
  }

  @protected
  LightingPreset sse_decode_lighting_preset(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_environment = sse_decode_f_32(deserializer);
    var var_sceneLux = sse_decode_f_32(deserializer);
    return LightingPreset(environment: var_environment, sceneLux: var_sceneLux);
  }

  @protected
  List<Light> sse_decode_list_light(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Light>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_light(deserializer));
    }
    return ans_;
  }

  @protected
  List<Material> sse_decode_list_material(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Material>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_material(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Submesh> sse_decode_list_submesh(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Submesh>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_submesh(deserializer));
    }
    return ans_;
  }

  @protected
  List<Texture> sse_decode_list_texture(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Texture>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_texture(deserializer));
    }
    return ans_;
  }

  @protected
  LusterBadge sse_decode_luster_badge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_designKey = sse_decode_String(deserializer);
    var var_submeshes = sse_decode_list_submesh(deserializer);
    var var_materials = sse_decode_list_material(deserializer);
    var var_textures = sse_decode_list_texture(deserializer);
    var var_struck =
        sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
          deserializer,
        );
    return LusterBadge(
      designKey: var_designKey,
      submeshes: var_submeshes,
      materials: var_materials,
      textures: var_textures,
      struck: var_struck,
    );
  }

  @protected
  LusterError sse_decode_luster_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_luster_error_kind(deserializer);
    var var_reason = sse_decode_String(deserializer);
    return LusterError(kind: var_kind, reason: var_reason);
  }

  @protected
  LusterErrorKind sse_decode_luster_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LusterErrorKind.values[inner];
  }

  @protected
  Material sse_decode_material(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_role = sse_decode_material_role(deserializer);
    var var_color = sse_decode_rgba(deserializer);
    var var_metallic = sse_decode_f_32(deserializer);
    var var_roughness = sse_decode_f_32(deserializer);
    var var_texture = sse_decode_opt_box_autoadd_u_32(deserializer);
    return Material(
      name: var_name,
      role: var_role,
      color: var_color,
      metallic: var_metallic,
      roughness: var_roughness,
      texture: var_texture,
    );
  }

  @protected
  MaterialRole sse_decode_material_role(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MaterialRole.values[inner];
  }

  @protected
  MintOptions sse_decode_mint_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_withoutHiddenFaces = sse_decode_bool(deserializer);
    var var_metalLines = sse_decode_bool(deserializer);
    return MintOptions(
      withoutHiddenFaces: var_withoutHiddenFaces,
      metalLines: var_metalLines,
    );
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Rgba sse_decode_rgba(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_r = sse_decode_f_32(deserializer);
    var var_g = sse_decode_f_32(deserializer);
    var var_b = sse_decode_f_32(deserializer);
    var var_a = sse_decode_f_32(deserializer);
    return Rgba(r: var_r, g: var_g, b: var_b, a: var_a);
  }

  @protected
  SceneCalibration sse_decode_scene_calibration(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exposure = sse_decode_f_32(deserializer);
    var var_lampUnit = sse_decode_f_32(deserializer);
    return SceneCalibration(exposure: var_exposure, lampUnit: var_lampUnit);
  }

  @protected
  Submesh sse_decode_submesh(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_material = sse_decode_u_32(deserializer);
    var var_positions = sse_decode_list_prim_f_32_strict(deserializer);
    var var_normals = sse_decode_list_prim_f_32_strict(deserializer);
    var var_texCoords = sse_decode_list_prim_f_32_strict(deserializer);
    var var_tangents = sse_decode_list_prim_f_32_strict(deserializer);
    var var_indices = sse_decode_list_prim_u_32_strict(deserializer);
    return Submesh(
      name: var_name,
      material: var_material,
      positions: var_positions,
      normals: var_normals,
      texCoords: var_texCoords,
      tangents: var_tangents,
      indices: var_indices,
    );
  }

  @protected
  Texture sse_decode_texture(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return Texture(width: var_width, height: var_height, rgba: var_rgba);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    Struck self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
      self,
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    MintRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MintRequestImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    Struck self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as StruckImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    MintRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MintRequestImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    Struck self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as StruckImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    MintRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as MintRequestImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    Struck self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as StruckImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mint_options(
    MintOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mint_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_rgba(Rgba self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rgba(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_camera(Camera self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.fov, serializer);
    sse_encode_f_32(self.distance, serializer);
  }

  @protected
  void sse_encode_coast(Coast self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.turn, serializer);
    sse_encode_f_32(self.velocity, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_finish(Finish self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.metallic, serializer);
    sse_encode_f_32(self.roughness, serializer);
    sse_encode_f_32(self.specular, serializer);
    sse_encode_bool(self.plated, serializer);
  }

  @protected
  void sse_encode_handling(Handling self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.spinPerPoint, serializer);
    sse_encode_f_32(self.tiltPerPoint, serializer);
    sse_encode_f_32(self.tiltLimit, serializer);
    sse_encode_f_32(self.restingTilt, serializer);
    sse_encode_f_32(self.restingSpin, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_light(Light self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_light_role(self.role, serializer);
    sse_encode_rgba(self.color, serializer);
    sse_encode_list_prim_f_32_strict(self.direction, serializer);
  }

  @protected
  void sse_encode_light_role(LightRole self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_lighting(Lighting self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_lighting_preset(
    LightingPreset self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.environment, serializer);
    sse_encode_f_32(self.sceneLux, serializer);
  }

  @protected
  void sse_encode_list_light(List<Light> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_light(item, serializer);
    }
  }

  @protected
  void sse_encode_list_material(List<Material> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_material(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_submesh(List<Submesh> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_submesh(item, serializer);
    }
  }

  @protected
  void sse_encode_list_texture(List<Texture> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_texture(item, serializer);
    }
  }

  @protected
  void sse_encode_luster_badge(LusterBadge self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.designKey, serializer);
    sse_encode_list_submesh(self.submeshes, serializer);
    sse_encode_list_material(self.materials, serializer);
    sse_encode_list_texture(self.textures, serializer);
    sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
      self.struck,
      serializer,
    );
  }

  @protected
  void sse_encode_luster_error(LusterError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_luster_error_kind(self.kind, serializer);
    sse_encode_String(self.reason, serializer);
  }

  @protected
  void sse_encode_luster_error_kind(
    LusterErrorKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_material(Material self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_material_role(self.role, serializer);
    sse_encode_rgba(self.color, serializer);
    sse_encode_f_32(self.metallic, serializer);
    sse_encode_f_32(self.roughness, serializer);
    sse_encode_opt_box_autoadd_u_32(self.texture, serializer);
  }

  @protected
  void sse_encode_material_role(MaterialRole self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mint_options(MintOptions self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.withoutHiddenFaces, serializer);
    sse_encode_bool(self.metalLines, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_rgba(Rgba self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.r, serializer);
    sse_encode_f_32(self.g, serializer);
    sse_encode_f_32(self.b, serializer);
    sse_encode_f_32(self.a, serializer);
  }

  @protected
  void sse_encode_scene_calibration(
    SceneCalibration self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.exposure, serializer);
    sse_encode_f_32(self.lampUnit, serializer);
  }

  @protected
  void sse_encode_submesh(Submesh self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.material, serializer);
    sse_encode_list_prim_f_32_strict(self.positions, serializer);
    sse_encode_list_prim_f_32_strict(self.normals, serializer);
    sse_encode_list_prim_f_32_strict(self.texCoords, serializer);
    sse_encode_list_prim_f_32_strict(self.tangents, serializer);
    sse_encode_list_prim_u_32_strict(self.indices, serializer);
  }

  @protected
  void sse_encode_texture(Texture self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class MintRequestImpl extends RustOpaque implements MintRequest {
  // Not to be used by end users
  MintRequestImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  MintRequestImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_MintRequest,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_MintRequest,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_MintRequestPtr,
  );

  /// The badge, once it is struck; a `cancelled` error once given up.
  Future<LusterBadge> badge() =>
      RustLib.instance.api.crateApiLusterMintRequestBadge(that: this);

  /// Gives the badge up: `badge` ends `cancelled`, and the engine stops if
  /// nobody else wants it. Nothing once it has come.
  void cancel() =>
      RustLib.instance.api.crateApiLusterMintRequestCancel(that: this);
}

@sealed
class StruckImpl extends RustOpaque implements Struck {
  // Not to be used by end users
  StruckImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  StruckImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Struck,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Struck,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_StruckPtr,
  );

  /// The badge as a glTF binary: see `LusterBadge.glb` in Dart.
  Future<Uint8List> glb({required double scale, required Rgba metal}) => RustLib
      .instance
      .api
      .crateApiLusterStruckGlb(that: this, scale: scale, metal: metal);
}
