// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/luster.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MintRequestPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequestPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_StruckPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruckPtr;

  @protected
  Struck
  dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    dynamic raw,
  );

  @protected
  MintRequest
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    dynamic raw,
  );

  @protected
  Struck
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    dynamic raw,
  );

  @protected
  MintRequest
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    dynamic raw,
  );

  @protected
  Struck
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    dynamic raw,
  );

  @protected
  MintRequest
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    dynamic raw,
  );

  @protected
  Struck
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MintOptions dco_decode_box_autoadd_mint_options(dynamic raw);

  @protected
  Rgba dco_decode_box_autoadd_rgba(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  Camera dco_decode_camera(dynamic raw);

  @protected
  Coast dco_decode_coast(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  Finish dco_decode_finish(dynamic raw);

  @protected
  Handling dco_decode_handling(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Light dco_decode_light(dynamic raw);

  @protected
  LightRole dco_decode_light_role(dynamic raw);

  @protected
  Lighting dco_decode_lighting(dynamic raw);

  @protected
  LightingPreset dco_decode_lighting_preset(dynamic raw);

  @protected
  List<Light> dco_decode_list_light(dynamic raw);

  @protected
  List<Material> dco_decode_list_material(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Submesh> dco_decode_list_submesh(dynamic raw);

  @protected
  List<Texture> dco_decode_list_texture(dynamic raw);

  @protected
  LusterBadge dco_decode_luster_badge(dynamic raw);

  @protected
  LusterError dco_decode_luster_error(dynamic raw);

  @protected
  LusterErrorKind dco_decode_luster_error_kind(dynamic raw);

  @protected
  Material dco_decode_material(dynamic raw);

  @protected
  MaterialRole dco_decode_material_role(dynamic raw);

  @protected
  MintOptions dco_decode_mint_options(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Rgba dco_decode_rgba(dynamic raw);

  @protected
  SceneCalibration dco_decode_scene_calibration(dynamic raw);

  @protected
  Submesh dco_decode_submesh(dynamic raw);

  @protected
  Texture dco_decode_texture(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Struck
  sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    SseDeserializer deserializer,
  );

  @protected
  MintRequest
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    SseDeserializer deserializer,
  );

  @protected
  Struck
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    SseDeserializer deserializer,
  );

  @protected
  MintRequest
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    SseDeserializer deserializer,
  );

  @protected
  Struck
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    SseDeserializer deserializer,
  );

  @protected
  MintRequest
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    SseDeserializer deserializer,
  );

  @protected
  Struck
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MintOptions sse_decode_box_autoadd_mint_options(SseDeserializer deserializer);

  @protected
  Rgba sse_decode_box_autoadd_rgba(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Camera sse_decode_camera(SseDeserializer deserializer);

  @protected
  Coast sse_decode_coast(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  Finish sse_decode_finish(SseDeserializer deserializer);

  @protected
  Handling sse_decode_handling(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Light sse_decode_light(SseDeserializer deserializer);

  @protected
  LightRole sse_decode_light_role(SseDeserializer deserializer);

  @protected
  Lighting sse_decode_lighting(SseDeserializer deserializer);

  @protected
  LightingPreset sse_decode_lighting_preset(SseDeserializer deserializer);

  @protected
  List<Light> sse_decode_list_light(SseDeserializer deserializer);

  @protected
  List<Material> sse_decode_list_material(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Submesh> sse_decode_list_submesh(SseDeserializer deserializer);

  @protected
  List<Texture> sse_decode_list_texture(SseDeserializer deserializer);

  @protected
  LusterBadge sse_decode_luster_badge(SseDeserializer deserializer);

  @protected
  LusterError sse_decode_luster_error(SseDeserializer deserializer);

  @protected
  LusterErrorKind sse_decode_luster_error_kind(SseDeserializer deserializer);

  @protected
  Material sse_decode_material(SseDeserializer deserializer);

  @protected
  MaterialRole sse_decode_material_role(SseDeserializer deserializer);

  @protected
  MintOptions sse_decode_mint_options(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Rgba sse_decode_rgba(SseDeserializer deserializer);

  @protected
  SceneCalibration sse_decode_scene_calibration(SseDeserializer deserializer);

  @protected
  Submesh sse_decode_submesh(SseDeserializer deserializer);

  @protected
  Texture sse_decode_texture(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    Struck self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    MintRequest self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    Struck self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    MintRequest self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    Struck self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    MintRequest self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    Struck self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mint_options(
    MintOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rgba(Rgba self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_camera(Camera self, SseSerializer serializer);

  @protected
  void sse_encode_coast(Coast self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_finish(Finish self, SseSerializer serializer);

  @protected
  void sse_encode_handling(Handling self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_light(Light self, SseSerializer serializer);

  @protected
  void sse_encode_light_role(LightRole self, SseSerializer serializer);

  @protected
  void sse_encode_lighting(Lighting self, SseSerializer serializer);

  @protected
  void sse_encode_lighting_preset(
    LightingPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_light(List<Light> self, SseSerializer serializer);

  @protected
  void sse_encode_list_material(List<Material> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_submesh(List<Submesh> self, SseSerializer serializer);

  @protected
  void sse_encode_list_texture(List<Texture> self, SseSerializer serializer);

  @protected
  void sse_encode_luster_badge(LusterBadge self, SseSerializer serializer);

  @protected
  void sse_encode_luster_error(LusterError self, SseSerializer serializer);

  @protected
  void sse_encode_luster_error_kind(
    LusterErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_material(Material self, SseSerializer serializer);

  @protected
  void sse_encode_material_role(MaterialRole self, SseSerializer serializer);

  @protected
  void sse_encode_mint_options(MintOptions self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_rgba(Rgba self, SseSerializer serializer);

  @protected
  void sse_encode_scene_calibration(
    SceneCalibration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_submesh(Submesh self, SseSerializer serializer);

  @protected
  void sse_encode_texture(Texture self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequestPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_luster_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequestPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequestPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_luster_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequest =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMintRequestPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruckPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_luster_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruckPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruckPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_luster_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruck =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStruckPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
